# Generated by Django 4.1.7 on 2023-04-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_sign_in',
            options={'verbose_name': '签到表', 'verbose_name_plural': '签到表'},
        ),
        migrations.AddField(
            model_name='student_sign_in',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
