# Generated by Django 4.1.7 on 2023-04-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '班级学生名单表', 'verbose_name_plural': '班级学生名单表'},
        ),
    ]
