# Generated by Django 4.1.7 on 2023-04-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_student_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='stu_teac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='学生姓名')),
                ('teacher', models.CharField(max_length=10, verbose_name='班主任姓名')),
                ('gender', models.IntegerField(choices=[('男生', 1), ('女生', 0)], verbose_name='性别')),
                ('stu_id_card', models.CharField(max_length=20, verbose_name='证件号')),
            ],
            options={
                'verbose_name': '学生信息表',
                'verbose_name_plural': '学生信息表',
            },
        ),
    ]
