# Generated by Django 4.1.7 on 2023-04-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_stu_teac'),
    ]

    operations = [
        migrations.CreateModel(
            name='excel_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_name', models.CharField(max_length=20, verbose_name='表名')),
                ('excel_file', models.FileField(upload_to='excel_file/', verbose_name='表文件')),
            ],
            options={
                'verbose_name': '学生excel表文件',
                'verbose_name_plural': '学生excel表文件',
            },
        ),
        migrations.AlterModelOptions(
            name='stu_teac',
            options={'verbose_name': '学生信息表表单', 'verbose_name_plural': '学生信息表表单'},
        ),
    ]
